package org.maple.tsc.models;

import java.util.Date;

public class CommentModel extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.owner_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.topic_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.super_comment_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long superCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.likes_count
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Integer likesCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.created_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Date createdDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Date lastUpdateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.is_active
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.owner_id
     *
     * @return the value of comment.owner_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.owner_id
     *
     * @param ownerId the value for comment.owner_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.topic_id
     *
     * @return the value of comment.topic_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.topic_id
     *
     * @param topicId the value for comment.topic_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.super_comment_id
     *
     * @return the value of comment.super_comment_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getSuperCommentId() {
        return superCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.super_comment_id
     *
     * @param superCommentId the value for comment.super_comment_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setSuperCommentId(Long superCommentId) {
        this.superCommentId = superCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.likes_count
     *
     * @return the value of comment.likes_count
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Integer getLikesCount() {
        return likesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.likes_count
     *
     * @param likesCount the value for comment.likes_count
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setLikesCount(Integer likesCount) {
        this.likesCount = likesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.created_dt
     *
     * @return the value of comment.created_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.created_dt
     *
     * @param createdDt the value for comment.created_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.last_update_dt
     *
     * @return the value of comment.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.last_update_dt
     *
     * @param lastUpdateDt the value for comment.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.is_active
     *
     * @return the value of comment.is_active
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.is_active
     *
     * @param isActive the value for comment.is_active
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    
    // ------------- Below is customized methods ------------------
    
    private UserDetailModel ownerDetailModel;
    
    private CommentModel superCommentModal;

	public UserDetailModel getOwnerDetailModel() {
		return ownerDetailModel;
	}

	public void setOwnerDetailModel(UserDetailModel ownerDetailModel) {
		this.ownerDetailModel = ownerDetailModel;
	}

	public CommentModel getSuperCommentModal() {
		return superCommentModal;
	}

	public void setSuperCommentModal(CommentModel superCommentModal) {
		this.superCommentModal = superCommentModal;
	}
    
}