package org.maple.tsc.models;

import java.util.Date;

public class CourseModel extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_number
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long courseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.description
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.created_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Date createdDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Date lastUpdateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.is_active
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_number
     *
     * @return the value of course.course_number
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getCourseNumber() {
        return courseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_number
     *
     * @param courseNumber the value for course.course_number
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setCourseNumber(Long courseNumber) {
        this.courseNumber = courseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.description
     *
     * @return the value of course.description
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.description
     *
     * @param description the value for course.description
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.created_dt
     *
     * @return the value of course.created_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.created_dt
     *
     * @param createdDt the value for course.created_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.last_update_dt
     *
     * @return the value of course.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.last_update_dt
     *
     * @param lastUpdateDt the value for course.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.is_active
     *
     * @return the value of course.is_active
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.is_active
     *
     * @param isActive the value for course.is_active
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
}