package org.maple.tsc.models;

public class StudentCourseXrefModel extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course_xref.id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course_xref.student_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course_xref.teacher_course_xref_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    private Long teacherCourseXrefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course_xref.score
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    private Float score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course_xref.id
     *
     * @return the value of student_course_xref.id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course_xref.id
     *
     * @param id the value for student_course_xref.id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course_xref.student_id
     *
     * @return the value of student_course_xref.student_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course_xref.student_id
     *
     * @param studentId the value for student_course_xref.student_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course_xref.teacher_course_xref_id
     *
     * @return the value of student_course_xref.teacher_course_xref_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public Long getTeacherCourseXrefId() {
        return teacherCourseXrefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course_xref.teacher_course_xref_id
     *
     * @param teacherCourseXrefId the value for student_course_xref.teacher_course_xref_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public void setTeacherCourseXrefId(Long teacherCourseXrefId) {
        this.teacherCourseXrefId = teacherCourseXrefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course_xref.score
     *
     * @return the value of student_course_xref.score
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course_xref.score
     *
     * @param score the value for student_course_xref.score
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public void setScore(Float score) {
        this.score = score;
    }
}