package org.maple.tsc.models;

import java.util.List;

public class TeacherCourseXrefModel extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course_xref.id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course_xref.teacher_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    private Long teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course_xref.course_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    private Long courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_course_xref.is_active
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course_xref.id
     *
     * @return the value of teacher_course_xref.id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course_xref.id
     *
     * @param id the value for teacher_course_xref.id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course_xref.teacher_id
     *
     * @return the value of teacher_course_xref.teacher_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course_xref.teacher_id
     *
     * @param teacherId the value for teacher_course_xref.teacher_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course_xref.course_id
     *
     * @return the value of teacher_course_xref.course_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course_xref.course_id
     *
     * @param courseId the value for teacher_course_xref.course_id
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_course_xref.is_active
     *
     * @return the value of teacher_course_xref.is_active
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_course_xref.is_active
     *
     * @param isActive the value for teacher_course_xref.is_active
     *
     * @mbg.generated Sat Apr 22 18:56:19 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    
    // ------------------ Below is customized methods -----------------------
    
    private CourseModel courseModel;
    
    private UserModel teacherModel;
    
    private List<UserModel> studentModelList;
    
	public CourseModel getCourseModel() {
		return courseModel;
	}

	public void setCourseModel(CourseModel courseModel) {
		this.courseModel = courseModel;
	}

	public UserModel getTeacherModel() {
		return teacherModel;
	}

	public void setTeacherModel(UserModel teacherModel) {
		this.teacherModel = teacherModel;
	}

	public List<UserModel> getStudentModelList() {
		return studentModelList;
	}

	public void setStudentModelList(List<UserModel> studentModelList) {
		this.studentModelList = studentModelList;
	}
}