package org.maple.tsc.models;

import java.util.Date;
import java.util.List;

public class TopicModel extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.owner_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.course_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.category_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.title
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.likes_count
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Integer likesCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.created_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Date createdDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Date lastUpdateDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.is_active
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Boolean isActive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.id
     *
     * @return the value of topic.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.id
     *
     * @param id the value for topic.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.owner_id
     *
     * @return the value of topic.owner_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.owner_id
     *
     * @param ownerId the value for topic.owner_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.course_id
     *
     * @return the value of topic.course_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.course_id
     *
     * @param courseId the value for topic.course_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.category_id
     *
     * @return the value of topic.category_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.category_id
     *
     * @param categoryId the value for topic.category_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.title
     *
     * @return the value of topic.title
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.title
     *
     * @param title the value for topic.title
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.content
     *
     * @param content the value for topic.content
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.likes_count
     *
     * @return the value of topic.likes_count
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Integer getLikesCount() {
        return likesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.likes_count
     *
     * @param likesCount the value for topic.likes_count
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setLikesCount(Integer likesCount) {
        this.likesCount = likesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.created_dt
     *
     * @return the value of topic.created_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Date getCreatedDt() {
        return createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.created_dt
     *
     * @param createdDt the value for topic.created_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.last_update_dt
     *
     * @return the value of topic.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.last_update_dt
     *
     * @param lastUpdateDt the value for topic.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.is_active
     *
     * @return the value of topic.is_active
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.is_active
     *
     * @param isActive the value for topic.is_active
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    
// ------------------ Below is customized methods ----------------------------
    private UserDetailModel ownerDetailModel;
    
    private CourseModel courseModel;
    
    private List<CommentModel> commentModelList;

	public UserDetailModel getOwnerDetailModel() {
		return ownerDetailModel;
	}

	public void setOwnerDetailModel(UserDetailModel ownerDetailModel) {
		this.ownerDetailModel = ownerDetailModel;
	}

	public CourseModel getCourseModel() {
		return courseModel;
	}

	public void setCourseModel(CourseModel courseModel) {
		this.courseModel = courseModel;
	}

	public List<CommentModel> getCommentModelList() {
		return commentModelList;
	}

	public void setCommentModelList(List<CommentModel> commentModelList) {
		this.commentModelList = commentModelList;
	}
    
	private CodetableModel categoryModel;

	public CodetableModel getCategoryModel() {
		return categoryModel;
	}

	public void setCategoryModel(CodetableModel categoryModel) {
		this.categoryModel = categoryModel;
	}
}