package org.maple.tsc.models;

import java.util.Date;

public class UserDetailModel extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.user_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.nickname
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.picture_path
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private String picturePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.birthday
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.grade
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.signature
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    private Date lastUpdateDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.id
     *
     * @return the value of user_detail.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.id
     *
     * @param id the value for user_detail.id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.user_id
     *
     * @return the value of user_detail.user_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.user_id
     *
     * @param userId the value for user_detail.user_id
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.nickname
     *
     * @return the value of user_detail.nickname
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.nickname
     *
     * @param nickname the value for user_detail.nickname
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.picture_path
     *
     * @return the value of user_detail.picture_path
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.picture_path
     *
     * @param picturePath the value for user_detail.picture_path
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath == null ? null : picturePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.birthday
     *
     * @return the value of user_detail.birthday
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.birthday
     *
     * @param birthday the value for user_detail.birthday
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.grade
     *
     * @return the value of user_detail.grade
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.grade
     *
     * @param grade the value for user_detail.grade
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.signature
     *
     * @return the value of user_detail.signature
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.signature
     *
     * @param signature the value for user_detail.signature
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setSignature(String signature) {
        this.signature = signature == null ? null : signature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.last_update_dt
     *
     * @return the value of user_detail.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public Date getLastUpdateDt() {
        return lastUpdateDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.last_update_dt
     *
     * @param lastUpdateDt the value for user_detail.last_update_dt
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    public void setLastUpdateDt(Date lastUpdateDt) {
        this.lastUpdateDt = lastUpdateDt;
    }
}