package org.maple.tsc.mappers;

import java.util.List;

import org.maple.tsc.models.CodetableModel;

public interface CodetableModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int insert(CodetableModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int insertSelective(CodetableModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    CodetableModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int updateByPrimaryKeySelective(CodetableModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table codetable
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int updateByPrimaryKey(CodetableModel record);
    
    // ------------- Below is customized methods -------------------
    
    CodetableModel selectByName(String name);
    
    List<CodetableModel> selectListByCategory(String category); 
}