package org.maple.tsc.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.maple.tsc.models.CourseModel;

public interface CourseModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int insert(CourseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int insertSelective(CourseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    CourseModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int updateByPrimaryKeySelective(CourseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int updateByPrimaryKey(CourseModel record);
    
    // ---------------- Below is customized methods -------------------------
    List<CourseModel> selectAll();
    
    int deleteByCourseNumber(Long courseNumber);
    
    CourseModel selectByCourseNumber(@Param("courseNumber") Long courseNumber);
}