package org.maple.tsc.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.maple.tsc.models.TopicModel;

public interface TopicModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int insert(TopicModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int insertSelective(TopicModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    TopicModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int updateByPrimaryKeySelective(TopicModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int updateByPrimaryKey(TopicModel record);
    
    // -------- Below is customized methods -------------
    
	List<TopicModel> selectListByUserId(Long userId);
	
	List<TopicModel> selectListByCourseId(Long courseId);
	
	List<TopicModel> selectAll();
	
	List<TopicModel> selectListByStudentIdAndCount(@Param("studentId")Long studentId, @Param("count")Integer count);
	
	List<TopicModel> selectListByTeacherIdAndCount(@Param("teacherId")Long teacherId, @Param("count")Integer count);
	
	List<TopicModel> selectListTopByCount(@Param("count") Integer count);
}