package org.maple.tsc.mappers;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.maple.tsc.models.UserModel;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    UserModel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 05 21:26:36 CST 2017
     */
    int updateByPrimaryKey(UserModel record);
    
    // ----------- Below is customized methods ----------------
    
    UserModel selectByAccountId(Long accountId);
    
    int delectByAccountId(Long accountId);
    
    List<UserModel> selectAllUsers();
    
    UserModel selectWithDetailById(Long id);
    
    int updateByAccountIdSelective(UserModel record);
    
    String selectPasswordByUserId(Long userId);
    
    int updateUserPasswordByUserId(@Param("userId") Long userId, @Param("password") String password);
}